import Head from 'next/head'

import PageNotFound from '@/modules/pageNotFound/PageNotFound'

const NotFoundPage = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <PageNotFound />
      </main>
    </>
  )
}

export default NotFoundPage
