import Head from 'next/head'
import React from 'react'

const AboutHero = React.lazy(() => import('@/modules/about/hero/AboutHero'))

const Mission = React.lazy(() => import('@/modules/about/mission/Mission'))

const CallToAction = React.lazy(() =>
  import('@/modules/about/callToAction/CallToAction')
)

const Purpose = React.lazy(() => import('@/modules/about/purpose/Purpose'))

const Quote = React.lazy(() => import('@/modules/about/quote/Quote'))

const About = () => {
  return (
    <>
      <Head>
        <title>Atalaso | About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <AboutHero />
        <Mission />
        <Purpose />
        <CallToAction />
        <Quote />
      </main>
    </>
  )
}

export default About
