import Head from 'next/head'

import AdsBanner from '@/modules/advertising/adsBanner/AdsBanner'
import AdsBenefits from '@/modules/advertising/adsBenefits/AdsBenefits'
import AdsCallToAction from '@/modules/advertising/adsCallToAction/AdsCallToAction'
import AdsFeatures from '@/modules/advertising/adsFeatures/AdsFeatures'
import AdsList from '@/modules/advertising/adsList/AdsList'
import AdsWall from '@/modules/advertising/adsWall/AdsWall'
import HeroAds from '@/modules/advertising/heroAds/HeroAds'

const advertising = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Advertising solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <HeroAds />
        <AdsBanner />
        <AdsBenefits />
        <AdsFeatures />
        <AdsWall />
        <AdsList />
        <AdsCallToAction />
      </main>
    </>
  )
}

export default advertising
