import Head from 'next/head'
import React from 'react'

const advertising = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Advertising solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Advertising</main>
    </>
  )
}

export default advertising
