import Head from 'next/head'

import ContactForm from '@/modules/contact/form/ContactForm'

const contact = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <ContactForm />
      </main>
    </>
  )
}

export default contact
