import Head from 'next/head'
import React from 'react'

const Hero = React.lazy(() => import('@/modules/home/hero/Hero'))

const LeadBenefits = React.lazy(() =>
  import('@/modules/home/leadBenefits/LeadBenefits')
)

const LeadGrid = React.lazy(() => import('@/modules/home/gridCards/GridCards'))

const Lead = React.lazy(() => import('@/modules/home/lead/Lead'))

const LeadWall = React.lazy(() => import('@/modules/home/leadWall/LeadWall'))

const LeadBanner = React.lazy(() =>
  import('@/modules/home/imageBanner/ImageBanner')
)

const LeadList = React.lazy(() => import('@/modules/home/leadList/LeadList'))

const LeadFeatures = React.lazy(() =>
  import('@/modules/home/LeadFeatures/LeadFeatures')
)

const LeadContact = React.lazy(() =>
  import('@/modules/home/leadContact/LeadContact')
)

export default function Home() {
  return (
    <>
      <Head>
        <title>Atalaso | Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <div>
          <Hero />
          <LeadGrid />
          <LeadBenefits />
          <LeadBanner />
          <Lead />
          <LeadWall />
          <LeadList />
          <LeadFeatures />
          <LeadContact />
        </div>
      </main>
    </>
  )
}
