import Head from 'next/head'
import React from 'react'

const PrivacyPolicy = React.lazy(() =>
  import('@/modules/privacy-policy/privacyPolicy/PrivacyPolicy')
)

const privacyPolicy = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Privacy policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PrivacyPolicy />
      </main>
    </>
  )
}

export default privacyPolicy
