import Head from 'next/head'

import CallToAction from '@/modules/web-development/callToAction/CallToAction'
import DevCases from '@/modules/web-development/devCases/DevCases'
import DevFeatures from '@/modules/web-development/devFeatures/DevFeatures'
import GridSection from '@/modules/web-development/devGrid/Grid'
import DevLead from '@/modules/web-development/devLead/DevLead'
import DevWall from '@/modules/web-development/devWall/DevWall'
import Hero from '@/modules/web-development/hero/Hero'

const solutions = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Web development solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <Hero />
        <DevLead />
        <DevWall />
        <GridSection />
        <DevCases />
        <DevFeatures />
        <CallToAction />
      </main>
    </>
  )
}

export default solutions
