import Head from 'next/head'
import React from 'react'

const Hero = React.lazy(() => import('@/modules/web-development/hero/Hero'))
const GridSection = React.lazy(() =>
  import('@/modules/web-development/devGrid/Grid')
)
const DevWall = React.lazy(() =>
  import('@/modules/web-development/devWall/DevWall')
)

const CallToAction = React.lazy(() =>
  import('@/modules/web-development/callToAction/CallToAction')
)

const DevList = React.lazy(() =>
  import('@/modules/web-development/devList/DevList')
)

const DevLead = React.lazy(() =>
  import('@/modules/web-development/devLead/DevLead')
)

const DevFeatures = React.lazy(() =>
  import('@/modules/web-development/devFeatures/DevFeatures')
)

const DevCases = React.lazy(() =>
  import('@/modules/web-development/devCases/DevCases')
)

const solutions = () => {
  return (
    <>
      <Head>
        <title>Atalaso | Web development solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role="main">
        <Hero />
        <GridSection />
        <DevLead />
        <DevWall />
        <DevList />
        <DevCases />
        <DevFeatures />
        <CallToAction />
      </main>
    </>
  )
}

export default solutions
